name = "verify"
defaultTargets = ["Outbox", "Harness"]

[[require]]
name = "aeneas"
git = "https://github.com/AeneasVerif/aeneas.git"
rev = "12a018bb0fab3333be572dadc0eab5108758552b"
subDir = "backends/lean"

[[lean_lib]]
name = "Outbox"

[[lean_lib]]
name = "Harness"
