use loom_proto::*;
use ts_rs::TS;
fn main() -> Result<(), Box<dyn std::error::Error>> {
    let output = std::env::args().nth(1).ok_or("usage: generate_ts OUTPUT")?;
    let declarations = [
        Lang::decl(),
        CasCodec::decl(),
        CasEntry::decl(),
        CasListRequest::decl(),
        CasPage::decl(),
        CasInspectRequest::decl(),
        CasLink::decl(),
        CasInspection::decl(),
        LlmRole::decl(),
        LlmMessage::decl(),
        LlmArgs::decl(),
        LlmChoice::decl(),
        LlmResult::decl(),
        ValueShape::decl(),
        ParamSig::decl(),
        ExportSig::decl(),
        TypeSig::decl(),
        Def::decl(),
        Diagnostic::decl(),
        DefineRequest::decl(),
        EvalRequest::decl(),
        CommandRequest::decl(),
        Response::decl(),
        Event::decl(),
        Actor::decl(),
        Snapshot::decl(),
        NameRevision::decl(),
        Desc::<Value>::decl(),
    ];
    let mut source = String::from(
        "// Generated by cargo run -p loom-proto --features codegen --example generate_ts -- OUTPUT\nexport type JsonValue = null | boolean | number | string | JsonValue[] | { [key: string]: JsonValue };\n",
    );
    for declaration in declarations {
        source.push_str("export ");
        source.push_str(&declaration);
        source.push('\n');
    }
    std::fs::write(output, source)?;
    Ok(())
}
