import subprocess, sys, re, os
def build(fname, imp, names, header):
    src = f"import {imp}\n" + "".join(f"#print axioms {n}\n" for n in names)
    open(fname,'w').write(src)
    out = subprocess.run(["lake","env","lean",fname],capture_output=True,text=True).stdout
    msgs = re.split(r"(?m)^(?='[^']+' depends on axioms)", out.strip())
    msgs = [m.strip() for m in msgs if m.strip()]
    assert len(msgs)==len(names), (msgs, names)
    body = f"import {imp}\n{header}\n"
    for n,m in zip(names,msgs):
        assert "sorryAx" not in m, m
        body += f"\n/-- info: {m} -/\n#guard_msgs in\n#print axioms {n}\n"
    open(fname,'w').write(body)
H="-- Build-enforced (generated by ../gen-axiom-guards.py): each report must match exactly, so a new `sorry` (sorryAx) or a new\n-- axiom anywhere under these theorems fails `lake env lean` and therefore check.sh."
build("AxiomsOutbox.lean","Outbox",["Outbox.Spec.at_most_once","Outbox.Spec.exactly_once","Outbox.Refinement.rust_step_exactly_once","Outbox.Refinement.rust_exactly_once"],H)
build("AxiomsHarness.lean","Harness",["Harness.Spec.permission_first","Harness.Spec.at_most_one_result","Harness.Spec.deny_final","Harness.Spec.closed_after_cancel","Harness.Spec.quiet_after_cancel","Harness.Refinement.step_refines","Harness.Refinement.rust_harness_correct","Harness.Refinement.rust_quiet_after_cancel","Harness.Codec.roundtrip","Harness.Codec.only_valid","Harness.Refinement.fix_agrees_without_cancel"],H+"\n-- The checker theorems (Harness.Check.*) use native_decide and are tests, not proofs.")
