#!/usr/bin/env python3
"""Regenerate lean/Axioms*.lean from the live `#print axioms` output. Run from verify/lean.

Each guard is a `#guard_msgs` block, so `lake env lean Axioms*.lean` (and check.sh)
fails if a report changes. Refuses to write any guard whose report contains sorryAx,
and only replaces a guard file after every check passed."""
import os, re, subprocess, sys, tempfile

HEADER = ("-- Build-enforced (generated by ../gen-axiom-guards.py): each report must match exactly,\n"
          "-- so a new `sorry` (sorryAx) or a new axiom under these theorems fails check.sh.")

def die(msg):
    sys.exit(f"gen-axiom-guards: {msg}")

def build(fname, imp, names, note=""):
    src = f"import {imp}\n" + "".join(f"#print axioms {n}\n" for n in names)
    with tempfile.NamedTemporaryFile("w", suffix=".lean", dir=".", delete=False) as probe:
        probe.write(src)
    try:
        run = subprocess.run(["lake", "env", "lean", probe.name], capture_output=True, text=True)
    finally:
        os.unlink(probe.name)
    if run.returncode != 0:
        die(f"{fname}: lean failed\n{run.stdout}{run.stderr}")
    msgs = [m.strip() for m in re.split(r"(?m)^(?='[^']+' depends on axioms)", run.stdout.strip()) if m.strip()]
    if len(msgs) != len(names):
        die(f"{fname}: expected {len(names)} reports, got {len(msgs)}")
    body = f"import {imp}\n{HEADER}\n{note}"
    for n, m in zip(names, msgs):
        if not m.startswith(f"'{n}' depends on axioms"):
            die(f"{fname}: report out of order for {n}: {m}")
        if "sorryAx" in m:
            die(f"{fname}: {n} depends on sorryAx")
        body += f"\n/-- info: {m} -/\n#guard_msgs in\n#print axioms {n}\n"
    tmp = fname + ".tmp"
    with open(tmp, "w") as out:
        out.write(body)
    os.replace(tmp, fname)

build("AxiomsOutbox.lean", "Outbox", [
    "Outbox.Spec.at_most_once", "Outbox.Spec.exactly_once",
    "Outbox.Refinement.rust_step_exactly_once", "Outbox.Refinement.rust_exactly_once"])
build("AxiomsHarness.lean", "Harness", [
    "Harness.Spec.permission_first", "Harness.Spec.at_most_one_result", "Harness.Spec.deny_final",
    "Harness.Spec.closed_after_cancel", "Harness.Spec.quiet_after_cancel",
    "Harness.Refinement.step_refines", "Harness.Refinement.rust_harness_correct",
    "Harness.Refinement.rust_quiet_after_cancel", "Harness.Refinement.fix_agrees_without_cancel",
    "Harness.Codec.roundtrip", "Harness.Codec.only_valid", "Harness.Codec.refuses"],
    "-- The checker theorems (Harness.Check.*) use native_decide and are tests, not proofs.\n")
print("gen-axiom-guards: wrote AxiomsOutbox.lean, AxiomsHarness.lean")
