[package]
name = "loom-rt"
version.workspace = true
edition.workspace = true
[dependencies]
loom-proto = { path = "../loom-proto" }
loom-store = { path = "../loom-store" }
loom-process = { path = "../loom-process" }
loom-model = { path = "../loom-model" }
anyhow = "1"
serde_json = "1"
blake3 = "1"
tokio = { version = "1", features = ["full"] }
futures = { version = "0.3", features = ["thread-pool"] }
uuid = { version = "1", features = ["v4"] }
wasmtime = { version = "=48.0.1", default-features = false, features = ["threads", "anyhow", "async", "cranelift", "incremental-cache", "runtime", "pooling-allocator", "parallel-compilation", "std", "wat"] }
rusqlite = "0.32"

serde = { version = "1", features = ["derive"] }
tempfile = "3"

libc = "0.2"

[build-dependencies]
anyhow = "1"
blake3 = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"

[dev-dependencies]
log = "0.4"
wat = "1"
